### Site Settings ###
title               : Ronald Onyango
description         : >- 
                      Crafting :hammer_and_pick: strategies that deliver,
                      understanding users to design what matters,
                      turning numbers into narratives,
                      and designing for delight, not just function.
url                 : https://ronaldonyango.github.io
baseurl             : ""            # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : ronaldonyango/ronaldonyango.github.io      # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : yousinix/portfolYOU
open_new_tab        : false                    # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Ronald Onyango
  image             : https://i.imgur.com/bcgYfUb.jpeg
  email             : ronaldoyw@gmail.com
  facebook          : ronaldonyango
  github            : ronaldonyango
  kaggle            : ronaldonyango
  linkedin          : ronaldonyango
  medium            : ronaldonyango
# stackoverflow     : your_user_id
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-N0CLMQ61L1


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments



### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
